[package]
name = "rdgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.0"
crossterm = "0.27.0"
display_tree = "1.1.2"
ptree = "0.4.0"
rand = "0.8.5"
thiserror = "1.0.57"
